// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VVCyberAware.Data;

#nullable disable

namespace VVCyberAware.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
<<<<<<<< HEAD:VVCyberAware/Migrations/20240308074002_Initial.Designer.cs
    [Migration("20240308074002_Initial")]
    partial class Initial
========
    [Migration("20240308091453_initial")]
    partial class initial
>>>>>>>> 646070451a622759bbd613657ced49b20a1c3493:VVCyberAware/Migrations/20240308091453_initial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VVCyberAware.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Info om bedrägeri",
                            Name = "Att skydda sig mot bedrägerier"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Digital säkerhet på företag",
                            Name = "Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Allmänt om cyberspionage",
                            Name = " Cyberspionage"
                        });
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswersJson = "{\"A) Ett legitimt f\\u00F6rs\\u00F6k fr\\u00E5n banken att skydda ditt konto\":false,\"B) En informationsinsamling f\\u00F6r en marknadsunders\\u00F6kning\":false,\"C) Ett potentiellt telefonbedr\\u00E4geri\":true}",
                            Explanation = "Banker och andra finansiella institutioner begär aldrig känslig information såsom kontonummer eller lösenord via telefon. Detta är ett klassiskt tecken på telefonbedrägeri.",
                            QuestionText = "Du får ett oväntat telefonsamtal från någon som påstår sig vara från din bank. Personen ber dig bekräfta ditt kontonummer och lösenord för att \"säkerställa din kontos säkerhet\" efter en påstådd säkerhetsincident. Hur bör du tolka denna situation?",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswersJson = "{\"A) Ett legitimt f\\u00F6rs\\u00F6k fr\\u00E5n banken att skydda ditt konto\":false,\"B) En informationsinsamling f\\u00F6r en marknadsunders\\u00F6kning\":false,\"C) Ett potentiellt telefonbedr\\u00E4geri\":true}",
                            Explanation = "Begäran om pengar, särskilt under omständigheter där två personer aldrig har träffats fysiskt, är ett vanligt tecken på romansbedrägeri.",
                            QuestionText = "Efter flera månader av daglig kommunikation med någon du träffade på en datingsida, börjar personen berätta om en plötslig finansiell kris och ber om din hjälp genom att överföra pengar. Vad indikerar detta mest sannolikt?",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            AnswersJson = "{\"A) Genomf\\u00F6ra omedelbar investering f\\u00F6r att inte missa m\\u00F6jligheten\":false,\"B) Investeringsbedr\\u00E4geri\":true,\"C) Beg\\u00E4ra mer information f\\u00F6r att utf\\u00F6ra en noggrann \\u2018\\u2019due diligence\":false}",
                            Explanation = "Erbjudanden som lovar hög avkastning med liten eller ingen risk, särskilt via oönskade e-postmeddelanden, är ofta tecken på investeringsbedrägerier",
                            QuestionText = "Du får ett e-postmeddelande/samtal om ett exklusivt erbjudande att investera i ett startup-företag som påstås ha en revolutionerande ny teknologi, med garantier om exceptionellt hög avkastning på mycket kort tid. Hur bör du förhålla dig till erbjudandet?\r\n",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            AnswersJson = "{\"A) Ett misstag av kreditkortsf\\u00F6retaget\":false,\"B) Kreditkortsbedr\\u00E4geri\":true,\"C) Obeh\\u00F6riga k\\u00F6p av en familjemedlem\":false}",
                            Explanation = "Oidentifierade transaktioner på ditt kreditkortsutdrag är en stark indikation på att ditt kortnummer har komprometterats och använts för obehöriga köp, vilket är typiskt för kreditkortsbedrägeri.",
                            QuestionText = "Efter en online-shoppingrunda märker du oidentifierade transaktioner på ditt kreditkortsutdrag från företag du aldrig handlat från. Vad indikerar detta mest sannolikt?",
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            AnswersJson = "{\"A) N\\u00E5gon erbjuder dig en gratis produkt i utbyte mot detaljerad personlig information.\":true,\"B) Din hund sk\\u00E4ller mer \\u00E4n vanligt\":false,\"C) Din granns bil ser annorlunda ut \\u00E4n den brukade.\":false}",
                            Explanation = "Denna fråga syftar till att öka medvetenheten om hur bedragare kan försöka manipulera människor i sina egna hem, ofta genom att erbjuda något som verkar vara för bra för att vara sant, som gratisprodukter eller tjänster, i utbyte mot personlig information eller finansiell data.",
                            QuestionText = "Vad är de vanligaste tecknen på att du kan vara måltavla för ett bedrägeri i hemmet?",
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            AnswersJson = "{\"A) Du f\\u00E5r en st\\u00F6rre \\u00E4n v\\u00E4ntad elr\\u00E4kning.\":false,\"B) Du m\\u00E4rker ov\\u00E4ntade transaktioner p\\u00E5 ditt bankkontoutdrag eller att dina kreditupplysningar visar konton du inte k\\u00E4nner till.\":true,\"C) Din favorit-TV-serie slutar pl\\u00F6tsligt s\\u00E4ndas.\":false}",
                            Explanation = " Denna fråga riktar in sig på att identifiera varningssignaler som kan tyda på att någon obehörigt använder din personliga information. Genom att känna till dessa tecken kan individer agera snabbt för att skydda sin finansiella hälsa och juridiska ställning.",
                            QuestionText = "Hur kan du upptäcka om någon har stulit din identitet?",
                            SubCategoryId = 6
                        },
                        new
                        {
                            Id = 7,
                            AnswersJson = "{\"A) Meddelandet erbjuder en kostnadsfri uppdatering till din programvara.\":false,\"B) Meddelandet inneh\\u00E5ller specifik och relevant information som bara du skulle k\\u00E4nna till.\":false,\"C) Meddelandet ber om omedelbar verifiering av personliga uppgifter via en l\\u00E4nk eller ett bifogat formul\\u00E4r.\":true}",
                            Explanation = "Denna fråga varnar för ett vanligt trick i nätfiske- och bluffmejl där avsändaren försöker få mottagaren att avslöja känslig information.",
                            QuestionText = "Hur kan du känna igen ett nätfiske- eller bluffmejl?",
                            SubCategoryId = 7
                        },
                        new
                        {
                            Id = 8,
                            AnswersJson = "{\"A) En investering som erbjuder regelbundna utbetalningar utan risk.\":true,\"B) En investering som st\\u00F6ds av stora, v\\u00E4lk\\u00E4nda finansinstitut.\":false,\"C) En investering som kr\\u00E4ver tid f\\u00F6r forskning och \\u00F6verv\\u00E4gande innan du engagerar dig.\":false}",
                            Explanation = "Denna fråga belyser hur löften om riskfria vinster ofta är ett tecken på investeringsbedrägeri, vilket är viktigt att känna till för att undvika ekonomiska förluster.",
                            QuestionText = "Vilket av följande är en varningssignal för investeringsbedrägeri på nätet?",
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 9,
                            AnswersJson = "{\"A) Betala l\\u00F6sensumman s\\u00E5 fort som m\\u00F6jligt.\":false,\"B) H\\u00E5lla ditt operativsystem och alla program uppdaterade med de senaste s\\u00E4kerhetsuppdateringarna.\":true,\"C) \\u00D6ppna alla bilagor du f\\u00E5r via e-post f\\u00F6r att kontrollera inneh\\u00E5llet.\":false}",
                            Explanation = "Att hålla programvara uppdaterad är avgörande för att förebygga ransomware-attacker eftersom det säkerställer att kända säkerhetsbrister åtgärdas.",
                            QuestionText = "Hur kan du bäst skydda dig mot ransomware-attacker?",
                            SubCategoryId = 9
                        },
                        new
                        {
                            Id = 10,
                            AnswersJson = "{\"A) Du mottar en detaljerad faktura f\\u00F6r en tj\\u00E4nst du regelbundet anv\\u00E4nder.\":false,\"B) Fakturan saknar detaljerad information och kontaktuppgifter.\":true,\"C) Du k\\u00E4nner igen f\\u00F6retagets namn och logotyp.\":false}",
                            Explanation = "En faktura som saknar detaljer eller kontaktuppgifter kan vara en indikation på en abonnemangsfälla eller en falsk faktura, vilket är en vanlig taktik bland bedragare.",
                            QuestionText = "Vilka är de främsta tecknen på att du kan ha drabbats av en abonnemangsfälla eller mottagit en falsk faktura?",
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 11,
                            AnswersJson = "{\"A) Genom att ignorera statistiken f\\u00F6r att fokusera p\\u00E5 annan verksamhet.\":false,\"B) Genom att anv\\u00E4nda statistiken f\\u00F6r att skr\\u00E4mma anst\\u00E4llda till b\\u00E4ttre efterlevnad.\":false,\"C) Genom att analysera trender och m\\u00F6nster f\\u00F6r att f\\u00F6rb\\u00E4ttra s\\u00E4kerhets\\u00E5tg\\u00E4rderna.\":true}",
                            Explanation = "Användning av statistik för att förstå och åtgärda säkerhetshot kan hjälpa företag att utveckla mer effektiva cybersäkerhetsstrategier och minska risken för brott.",
                            QuestionText = "På vilket sätt kan statistik över cyberbrott påverka ett företags förhållningssätt till cybersäkerhet?",
                            SubCategoryId = 11
                        },
                        new
                        {
                            Id = 12,
                            AnswersJson = "{\"A) Utbildning i digital s\\u00E4kerhet f\\u00F6r alla anst\\u00E4llda\":true,\"B) Installera en starkare brandv\\u00E4gg\":false,\"C) Byta ut all IT-utrustning\":false}",
                            Explanation = "Utbildning i digital säkerhet är avgörande för att hjälpa anställda att känna igen och undvika säkerhetshot som phishing, vilket är en vanlig attackvektor.",
                            QuestionText = "Inom företaget märker man att konfidentiella dokument regelbundet läcker ut till konkurrenter. Efter en intern granskning upptäcks det att en anställd omedvetet har installerat skadlig programvara genom att klicka på en länk i ett phishing-e-postmeddelande. Vilken åtgärd bör prioriteras för att förhindra framtida incidenter?",
                            SubCategoryId = 12
                        },
                        new
                        {
                            Id = 13,
                            AnswersJson = "{\"A) Informera alla anv\\u00E4ndare om s\\u00E5rbarheten och rekommendera tempor\\u00E4ra skydds\\u00E5tg\\u00E4rder\":true,\"B) Ignorera problemet tills en patch kan utvecklas\":false,\"C) St\\u00E4nga ner tj\\u00E4nsten tillf\\u00E4lligt\":false}",
                            Explanation = "Transparent kommunikation och rådgivning om tillfälliga åtgärder är avgörande för att skydda användarna medan en permanent lösning utvecklas.",
                            QuestionText = "Inom företaget upptäcks det en sårbarhet i vår programvara som kunde möjliggöra obehörig åtkomst till användardata. Företaget har inte omedelbart en lösning. Vilken är den mest lämpliga första åtgärden?",
                            SubCategoryId = 13
                        },
                        new
                        {
                            Id = 14,
                            AnswersJson = "{\"A) En enskild hackare med ett personligt vendetta\":false,\"B) En konkurrerande f\\u00F6retagsentitet\":false,\"C) Organiserade cyberbrottsliga grupper\":true}",
                            Explanation = "DDoS-attacker kräver ofta betydande resurser och koordinering, vilket är karakteristiskt för organiserade cyberbrottsliga grupper.",
                            QuestionText = "Vårt företag blir måltavla för en DDoS-attack som överväldigar våra servers och gör våra tjänster otillgängliga för kunder. Vilken typ av aktör är mest sannolikt ansvarig för denna typ av attack?",
                            SubCategoryId = 14
                        },
                        new
                        {
                            Id = 15,
                            AnswersJson = "{\"A) \\u00C5terg\\u00E5 till kontorsarbete\":false,\"B) Inf\\u00F6ra striktare l\\u00F6senordspolicyer och tv\\u00E5faktorsautentisering f\\u00F6r fj\\u00E4rr\\u00E5tkomst\":true,\"C) F\\u00F6rbjuda anv\\u00E4ndning av personliga enheter f\\u00F6r arbete\":false}",
                            Explanation = "Stärkt autentisering är kritisk för att säkra fjärråtkomst och skydda mot obehörig åtkomst i en distribuerad arbetsmiljö.",
                            QuestionText = "Med övergången till distansarbete upptäcker vårt företag en ökning av säkerhetsincidenter, inklusive obehörig åtkomst till företagsdata. Vilken åtgärd bör företaget vidta för att adressera denna nya riskmiljö?",
                            SubCategoryId = 15
                        },
                        new
                        {
                            Id = 16,
                            AnswersJson = "{\"A) Phishing\":false,\"B) Ransomware\":true,\"C) Spyware\":false}",
                            Explanation = "Ransomware-angrepp involverar kryptering av offerdata och kräver lösen för dekryptering, vilket är särskilt skadligt för kritiska sektorer som hälsovård.",
                            QuestionText = "Hälsovårdsmyndigheten utsätts för ett cyberangrepp som krypterar patientdata och kräver lösen för att återställa åtkomsten. Vilken typ av angrepp har de sannolikt blivit utsatta för?",
                            SubCategoryId = 16
                        },
                        new
                        {
                            Id = 17,
                            AnswersJson = "{\"A) Spyware\":false,\"B) Ransomware\":true,\"C) Adware\":false}",
                            Explanation = "Maersk utsattes för NotPetya ransomware-angreppet, som ledde till omfattande störningar och förluster genom att kryptera",
                            QuestionText = "Det globala fraktbolaget Maersk blev offer för ett omfattande cyberangrepp som avsevärt störde deras verksamhet världen över. Vilken typ av malware var primärt ansvarig för denna incident?",
                            SubCategoryId = 17
                        },
                        new
                        {
                            Id = 18,
                            AnswersJson = "{\"A) Att f\\u00F6rb\\u00E4ttra f\\u00F6retagets interna kommunikationsstrategier.\":false,\"B) Att manipulera individer till att avsl\\u00F6ja konfidentiell information eller utf\\u00F6ra handlingar som komprometterar s\\u00E4kerheten.\":true,\"C) Att uppgradera f\\u00F6retagets h\\u00E5rdvara och mjukvara f\\u00F6r att f\\u00F6rb\\u00E4ttra s\\u00E4kerheten.\":false}",
                            Explanation = "Social engineering använder mänskliga interaktioner för att få tillgång till konfidentiell information eller system. Att förstå detta är viktigt för att skydda sig.",
                            QuestionText = "Vad är det primära målet med social engineering inom cybersäkerhet?",
                            SubCategoryId = 18
                        },
                        new
                        {
                            Id = 19,
                            AnswersJson = "{\"A) \\u00D6ppna alla e-postmeddelanden f\\u00F6r att snabbt avg\\u00F6ra deras giltighet.\":false,\"B) Anv\\u00E4nda ett komplicerat l\\u00F6senord f\\u00F6r alla onlinekonton.\":false,\"C) Inte klicka p\\u00E5 misst\\u00E4nkta l\\u00E4nkar eller bilagor i e-postmeddelanden fr\\u00E5n ok\\u00E4nda avs\\u00E4ndare.\":true}",
                            Explanation = "Att undvika att klicka på misstänkta länkar eller bilagor är en effektiv strategi för att skydda sig mot nätfiske och skräppost.",
                            QuestionText = "Vilken är den bästa metoden för att skydda sig mot nätfiske och skräppost?",
                            SubCategoryId = 19
                        },
                        new
                        {
                            Id = 20,
                            AnswersJson = "{\"A) Att skicka virus genom e-postmeddelanden.\":false,\"B) Att genomf\\u00F6ra bedr\\u00E4gliga telefonsamtal d\\u00E4r avs\\u00E4ndaren utger sig f\\u00F6r att vara fr\\u00E5n en trov\\u00E4rdig organisation f\\u00F6r att f\\u00E5 tag p\\u00E5 k\\u00E4nslig information.\":true,\"C) Att anv\\u00E4nda fysisk s\\u00E4kerhetsutrustning f\\u00F6r att skydda ett n\\u00E4tverk.\":false}",
                            Explanation = "Vishing involverar bedrägliga telefonsamtal för att lura mottagaren att avslöja personlig eller finansiell information.",
                            QuestionText = "Vad karaktäriserar ett vishing-angrepp?",
                            SubCategoryId = 20
                        },
                        new
                        {
                            Id = 21,
                            AnswersJson = "{\"A) Ge ut personlig information f\\u00F6r att verifiera avs\\u00E4ndarens identitet.\":false,\"B) Notera avs\\u00E4ndarens information och avsluta samtalet omedelbart; rapportera sedan f\\u00F6rs\\u00F6ket till l\\u00E4mpliga myndigheter.\":true,\"C) F\\u00F6rs\\u00F6k att sp\\u00E5ra samtalet sj\\u00E4lv och konfrontera avs\\u00E4ndaren.\":false}",
                            Explanation = "Det bästa sättet att hantera ett vishing-försök är att notera avsändarens information, avsluta samtalet omedelbart och sedan rapportera försöket.",
                            QuestionText = "Vilket är det bästa sättet att hantera ett misstänkt vishing-försök?",
                            SubCategoryId = 21
                        },
                        new
                        {
                            Id = 22,
                            AnswersJson = "{\"A) Omedelbart f\\u00F6lja instruktionerna i mailet f\\u00F6r att visa lydnad.\":false,\"B) Kontrollera avs\\u00E4ndarens e-postadress noggrant och verifiera f\\u00F6rfr\\u00E5gan genom en annan kommunikationskanal.\":true,\"C) Skicka konfidentiell information som beg\\u00E4rs f\\u00F6r att uppr\\u00E4tth\\u00E5lla goda relationer med VD:n.\":false}",
                            Explanation = "Att känna igen och reagera korrekt på försök till VD-bedrägerier är viktigt. Kontrollera avsändarens identitet och verifiera alla förfrågningar på ett säkert sätt för att undvika bedrägerier.",
                            QuestionText = "Vad bör du göra för att korrekt identifiera ett falskt VD-mejl?",
                            SubCategoryId = 22
                        },
                        new
                        {
                            Id = 23,
                            AnswersJson = "{\"A) K\\u00F6p omedelbart presentkort och skicka koder till avs\\u00E4ndaren f\\u00F6r att snabbt svara p\\u00E5 deras beg\\u00E4ran.\":false,\"B) Ignorera alla f\\u00F6rfr\\u00E5gningar om att k\\u00F6pa eller skicka presentkort som kommer via e-post eller telefon.\":true,\"C) Be om ytterligare personlig information fr\\u00E5n avs\\u00E4ndaren f\\u00F6r att bekr\\u00E4fta deras identitet.\":false}",
                            Explanation = "Övertalningsangrepp och presentkortsbluffar använder manipulation för att lura individer. Det bästa försvaret är att inte svara på dessa förfrågningar och rapportera dem till lämpliga myndigheter.",
                            QuestionText = "Vad är det bästa försvaret mot övertalningsangrepp och presentkortsbluffar?",
                            SubCategoryId = 23
                        },
                        new
                        {
                            Id = 24,
                            AnswersJson = "{\"A) Virus beh\\u00F6ver en v\\u00E4rdfil f\\u00F6r att spridas, medan maskar kan sprida sig sj\\u00E4lvst\\u00E4ndigt och trojaner maskerar sig som legitima program.\":true,\"B) Trojaner sprider sig sj\\u00E4lvst\\u00E4ndigt via n\\u00E4tverk, medan virus och maskar \\u00E4r ofarliga filer.\":false,\"C) Maskar \\u00E4r godartade program som hj\\u00E4lper till att skydda datorer mot virus.\":false}",
                            Explanation = "Det primära skiljetecknet är att virus behöver en värdfil för att spridas, maskar sprider sig självständigt, och trojaner utger sig för att vara legitima program.",
                            QuestionText = "Vilket är det primära skiljetecknet mellan virus, maskar och trojaner?",
                            SubCategoryId = 24
                        },
                        new
                        {
                            Id = 25,
                            AnswersJson = "{\"A) Att endast anv\\u00E4nda tr\\u00E5dl\\u00F6sa n\\u00E4tverk.\":false,\"B) Att genomf\\u00F6ra regelbundna s\\u00E4kerhetsgranskningar och uppdatera s\\u00E4kerhetssystem.\":true,\"C) Att h\\u00E5lla n\\u00E4tverket \\u00F6ppet f\\u00F6r att kunna sp\\u00E5ra potentiella hackare.\":false}",
                            Explanation = "Regelbundna säkerhetsgranskningar och uppdateringar av säkerhetssystem är mest effektiva för att förebygga nätverksintrång.",
                            QuestionText = "Vilken metod anses vara mest effektiv för att förebygga nätverksintrång?",
                            SubCategoryId = 25
                        },
                        new
                        {
                            Id = 26,
                            AnswersJson = "{\"A) Ignorera varningstecknen och hoppas att problemet l\\u00F6ser sig sj\\u00E4lvt.\":false,\"B) Isolera det drabbade systemet och bed\\u00F6m omfattningen av intr\\u00E5nget.\":true,\"C) Omedelbart informera alla sociala medier om intr\\u00E5nget.\":false}",
                            Explanation = "De första stegen inkluderar att isolera det drabbade systemet och bedöma omfattningen av intrånget.",
                            QuestionText = "Vilka är de första stegen du bör ta vid upptäckt av ett dataintrång?",
                            SubCategoryId = 26
                        },
                        new
                        {
                            Id = 27,
                            AnswersJson = "{\"A) \\u00C4ndra alla l\\u00F6senord omedelbart.\":false,\"B) St\\u00E4ng av alla datorer och n\\u00E4tverksutrustning.\":false,\"C) Identifiera och isolera de drabbade delarna av n\\u00E4tverket.\":true}",
                            Explanation = "Det första steget bör vara att identifiera och isolera de drabbade delarna av nätverket för att förhindra ytterligare skada.",
                            QuestionText = "Vad bör vara ditt första steg om du upptäcker att ditt företags nätverk har blivit hackat?",
                            SubCategoryId = 27
                        },
                        new
                        {
                            Id = 28,
                            AnswersJson = "{\"A) Genom fysisk s\\u00E4kerhet och \\u00F6vervakningskameror.\":false,\"B) Genom phishing-e-post, svaga l\\u00F6senord och os\\u00E4kra n\\u00E4tverk.\":true,\"C) Genom att endast anv\\u00E4nda godk\\u00E4nd programvara.\":false}",
                            Explanation = "De vanligaste vägarna in för cyberangripare inkluderar phishing-e-post, svaga lösenord och osäkra nätverk.",
                            QuestionText = "Vilka är de vanligaste vägarna in för cyberangripare?",
                            SubCategoryId = 28
                        },
                        new
                        {
                            Id = 29,
                            AnswersJson = "{\"A) Betala omedelbart l\\u00F6sensumman f\\u00F6r att \\u00E5terf\\u00E5 tillg\\u00E5ng till filerna.\":false,\"B) Ignorera alla misst\\u00E4nkta e-postmeddelanden och h\\u00E5lla alla system uppdaterade.\":true,\"C) Lagra k\\u00E4nslig information p\\u00E5 l\\u00E4ttillg\\u00E4ngliga offentliga servrar.\":false}",
                            Explanation = "Den mest effektiva åtgärden för att skydda sig mot utpressningsvirus är att ignorera misstänkta e-postmeddelanden och hålla alla system uppdaterade.",
                            QuestionText = "Vad är den mest effektiva åtgärden för att skydda sig mot utpressningsvirus?",
                            SubCategoryId = 29
                        },
                        new
                        {
                            Id = 30,
                            AnswersJson = "{\"A) Fysisk skada p\\u00E5 serverutrustning.\":false,\"B) DDoS-attacker som \\u00F6verv\\u00E4ldigar serverns resurser.\":true,\"C) Attacker som endast riktar sig mot b\\u00E4rbara enheter.\":false}",
                            Explanation = "Den vanligaste typen av attack mot servrar är DDoS-attacker som överväldigar serverns resurser.",
                            QuestionText = "Vilken är den vanligaste typen av attack mot servrar?",
                            SubCategoryId = 30
                        },
                        new
                        {
                            Id = 31,
                            AnswersJson = "{\"A) De involverar oftast fysiska inbrott i datamilj\\u00F6er.\":false,\"B) De \\u00E4r vanligtvis riktade mot mobila betalningssystem.\":false,\"C) De utnyttjar ofta social engineering och phishing.\":true}",
                            Explanation = "Ett vanligt karaktärsdrag för cyberangrepp i Norden är att de ofta utnyttjar social engineering och phishing.",
                            QuestionText = "Vilket karaktärsdrag är vanligt för cyberangrepp i Norden?",
                            SubCategoryId = 31
                        },
                        new
                        {
                            Id = 32,
                            AnswersJson = "{\"A) Avancerade kryptografiska system.\":false,\"B) Phishing, malware och n\\u00E4tverkssniffning.\":true,\"C) Lagliga programvaror f\\u00F6r databasadministration.\":false}",
                            Explanation = "De mest använda verktygen av IT-brottslingar inkluderar phishing, malware och nätverkssniffning.",
                            QuestionText = "Vilka är de mest använda verktygen av IT-brottslingar?",
                            SubCategoryId = 32
                        },
                        new
                        {
                            Id = 33,
                            AnswersJson = "{\"A) De \\u00E4r alla exempel p\\u00E5 statligt sponsrade hackningsf\\u00F6rs\\u00F6k.\":false,\"B) De involverar alla skadlig programvara som sprids automatiskt \\u00F6ver n\\u00E4tverk.\":true,\"C) De \\u00E4r k\\u00E4nda fall av dataintr\\u00E5ng via sociala medier.\":false}",
                            Explanation = "Mirai, Wannacry och incidenten i Düsseldorf har gemensamt att de involverar skadlig programvara som sprids automatiskt över nätverk.",
                            QuestionText = "Vad har Mirai, Wannacry och incidenten i Düsseldorf gemensamt?",
                            SubCategoryId = 33
                        },
                        new
                        {
                            Id = 34,
                            AnswersJson = "{\"A) Otillr\\u00E4cklig lokal lagring.\":false,\"B) Brister i fysisk s\\u00E4kerhet hos molnleverant\\u00F6rer.\":false,\"C) Otillr\\u00E4ckliga \\u00E5tkomstkontroller och datakryptering.\":true}",
                            Explanation = "Den största säkerhetsutmaningen med molntjänster är otillräckliga åtkomstkontroller och datakryptering.",
                            QuestionText = "Vad är den största säkerhetsutmaningen med molntjänster?",
                            SubCategoryId = 34
                        },
                        new
                        {
                            Id = 35,
                            AnswersJson = "{\"A) Cyberkriminalitet\":false,\"B) Cyberspionage\":true,\"C) Cyberterrorism\":false}",
                            Explanation = "Cyberspionage avser aktiviteter där aktörer, ofta statliga, engagerar sig i övervakning och datainsamling genom cybermedel för att erhålla hemlig information utan målets medgivande.",
                            QuestionText = "Regeringen upptäcker att känslig politisk kommunikation har läckt och misstänker elektronisk övervakning. Vilket fenomen beskriver bäst denna situation?",
                            SubCategoryId = 35
                        },
                        new
                        {
                            Id = 36,
                            AnswersJson = "{\"A) Social ingenj\\u00F6rskonst\":false,\"B) Mass\\u00F6vervakning\":false,\"C) Riktade cyberattacker\":true}",
                            Explanation = "Riktade cyberattacker som utnyttjar Zero-day sårbarheter är en avancerad metod för cyberspionage, specifikt riktad för att komma åt känslig information genom att utnyttja tidigare okända sårbarheter.",
                            QuestionText = "Regeringen blir varse om en sofistikerad skadeprogramskampanj som utnyttjar Zero-day sårbarheter för att infiltrera deras nätverk och stjäla oerhört viktig data. Vilken metod för cyberspionage används sannolikt här?",
                            SubCategoryId = 36
                        },
                        new
                        {
                            Id = 37,
                            AnswersJson = "{\"A) GDPR\":false,\"B) S\\u00E4kerhetsskyddslagen\":true,\"C) IT-s\\u00E4kerhetslagen\":false}",
                            Explanation = "Säkerhetsskyddslagen är en svensk lagstiftning som syftar till att skydda nationellt känslig information och ställer krav på säkerhetsskyddsåtgärder för verksamheter av betydelse för Sveriges säkerhet.",
                            QuestionText = "Regeringen i Sverige ökar sitt interna säkerhetsprotokoll för att skydda sig mot utländska underrättelsetjänsters infiltration. Vilken lagstiftning ger ramverket för detta skydd?",
                            SubCategoryId = 37
                        },
                        new
                        {
                            Id = 38,
                            AnswersJson = "{\"A) Oberoende hackare\":false,\"B) Aktivistgrupper\":false,\"C) Statssponsrade hackers\":true}",
                            Explanation = "Statssponsrade hackers är aktörer som arbetar på uppdrag av eller med stöd från en regering, ofta riktat mot strategiska mål som forskningsdata för att få strategiska fördelar.",
                            QuestionText = "Lunds universitet upptäcker att forskningsdata om ny teknologi har stulits. Undersökningar tyder på en välorganiserad grupp med kopplingar till en utländsk stat. Vilken typ av aktör ligger sannolikt bakom detta?",
                            SubCategoryId = 38
                        },
                        new
                        {
                            Id = 39,
                            AnswersJson = "{\"A) Att rekrytera nya medarbetare via digitala kanaler.\":false,\"B) Att \\u00F6vertyga befintliga anst\\u00E4llda eller individer att medvetet l\\u00E4cka information eller ge tillg\\u00E5ng till system.\":true,\"C) Att erbjuda gratis programvara till f\\u00F6retag som en del av en marknadsf\\u00F6ringskampanj.\":false}",
                            Explanation = "Värvningsförsök innebär att övertyga befintliga anställda eller individer att medvetet läcka information eller ge tillgång till system.",
                            QuestionText = "Vad avses med värvningsförsök inom cybersäkerhetskontexten?",
                            SubCategoryId = 39
                        },
                        new
                        {
                            Id = 40,
                            AnswersJson = "{\"A) Utbyte av f\\u00F6retagsinformation mellan konkurrerande f\\u00F6retag.\":false,\"B) Anv\\u00E4ndning av digital teknik f\\u00F6r att otillb\\u00F6rligt inh\\u00E4mta konkurrenters f\\u00F6retagshemligheter.\":true,\"C) Offentligg\\u00F6rande av f\\u00F6retagsresultat p\\u00E5 sociala medier.\":false}",
                            Explanation = "Affärsspionage i en digital miljö definieras som användningen av digital teknik för att otillbörligt inhämta konkurrenters företagshemligheter.",
                            QuestionText = "Hur definieras affärsspionage i en digital miljö?",
                            SubCategoryId = 40
                        },
                        new
                        {
                            Id = 41,
                            AnswersJson = "{\"A) Att \\u00F6ka f\\u00F6rs\\u00E4ljningen av en specifik produkt.\":false,\"B) Att sprida desinformation och p\\u00E5verka allm\\u00E4nhetens \\u00E5sikter eller val.\":true,\"C) Att f\\u00F6rb\\u00E4ttra f\\u00F6retagets varum\\u00E4rkesimage genom reklam.\":false}",
                            Explanation = "Målet med digitala påverkanskampanjer är att sprida desinformation och påverka allmänhetens åsikter eller val.",
                            QuestionText = "Vad är målet med digitala påverkanskampanjer?",
                            SubCategoryId = 41
                        },
                        new
                        {
                            Id = 42,
                            AnswersJson = "{\"A) Att marknadsf\\u00F6ra Sverige som en turistdestination.\":false,\"B) Att samla in och analysera information om cyberhot och st\\u00E4rka nationens cyberf\\u00F6rsvar.\":true,\"C) Att erbjuda IT-support till sm\\u00E5 och medelstora f\\u00F6retag.\":false}",
                            Explanation = "Den svenska underrättelsetjänstens roll i landets cyberförsvar är att samla in och analysera information om cyberhot och därmed stärka nationens säkerhet.",
                            QuestionText = "Vilken roll spelar den svenska underrättelsetjänsten i landets cyberförsvar?",
                            SubCategoryId = 42
                        },
                        new
                        {
                            Id = 43,
                            AnswersJson = "{\"A) 5G-utbyggnaden \\u00E4r bara relevant f\\u00F6r mobiloperat\\u00F6rer och p\\u00E5verkar inte signalspaning.\":false,\"B) Utbyggnaden av 5G st\\u00E4ller h\\u00F6gre krav p\\u00E5 informationss\\u00E4kerhet och kan p\\u00E5verka metoder f\\u00F6r signalspaning.\":true,\"C) 5G \\u00E4r endast viktigt f\\u00F6r f\\u00F6rb\\u00E4ttrad spelupplevelse och har inget samband med signalspaning eller informationss\\u00E4kerhet.\":false}",
                            Explanation = "Utbyggnaden av 5G ställer högre krav på informationssäkerhet och kan påverka metoder för signalspaning.",
                            QuestionText = "Hur relaterar signalspaning och informationssäkerhet till utbyggnaden av 5G-nätverk?",
                            SubCategoryId = 43
                        },
                        new
                        {
                            Id = 44,
                            AnswersJson = "{\"A) Anv\\u00E4nda endast antivirusprogram.\":false,\"B) Blockera all inkommande trafik fr\\u00E5n utlandet.\":false,\"C) Dela underr\\u00E4ttelseinformation med andra organisationer.\":true}",
                            Explanation = "Att dela underrättelseinformation hjälper organisationer att identifiera och motverka cyberspionage mer effektivt genom förbättrad medvetenhet och koordinerade försvarsåtgärder.",
                            QuestionText = "Vilken åtgärd är mest effektiv för samverkan mot cyberspionage?",
                            SubCategoryId = 44
                        });
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SegmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIsComplete")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Segments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Del 1",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Del 2",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Del 3",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Del 1",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Del 2",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Del 3",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Del 4",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Del 1",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Del 2",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Del 3",
                            UserIsComplete = "[]"
                        });
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SubCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kreditkortsbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Romansbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Investeringsbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Telefonbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bedrägerier i hemmet",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Identitetsstöld",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Nätfiske och bluffmejl",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Investeringsbedrägeri på nätet",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Abonnemangsfällor och falska fakturor",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ransomware",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 11,
                            Description = "Statistik och förhållningssätt",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Digital säkerhet på företag",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Risker och beredskap",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 14,
                            Description = "Aktörer inom cyberbrott",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ökad digital närvaro och distansarbete",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 16,
                            Description = "Cyberangrepp mot känsliga sektorer",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Cyberrånet mot Mersk",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 18,
                            Description = "Social engineering",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 19,
                            Description = "Nätfiske och skräppost",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 20,
                            Description = "Vishing",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 21,
                            Description = "Varning för vishing",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 22,
                            Description = "Identifiera VD-mejl",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 23,
                            Description = "Öneangrepp och presentkortsbluffar",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "Virus, maskar och trojaner",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 25,
                            Description = "Nätverksintrång",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 26,
                            Description = "Dataintrång",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 27,
                            Description = "Hackad!",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 28,
                            Description = "Vägarna in",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 29,
                            Description = "Utpressningsvirus",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 30,
                            Description = "Attacker mot servrar",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 31,
                            Description = "Cyberangrepp i Norden",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 32,
                            Description = "It-brottslingarnas verktyg",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 33,
                            Description = "Mirai, Wannacry och fallet Düsseldorf",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 34,
                            Description = "De sårbara molnen",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 35,
                            Description = "Allmänt om cyberspionage",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 36,
                            Description = "Metoder för cyberspionage",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 37,
                            Description = "Säkerhetsskyddslagen",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 38,
                            Description = "Cyberspionagets aktörer",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 39,
                            Description = "Värvningsförsök",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 40,
                            Description = "Affärsspionage",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 41,
                            Description = "Påverkanskampanjer",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 42,
                            Description = "Svensk underrättelsetjänst och cyberförsvar",
                            SegmentId = 10
                        },
                        new
                        {
                            Id = 43,
                            Description = "Signalspaning, informationssäkerhet och 5G",
                            SegmentId = 10
                        },
                        new
                        {
                            Id = 44,
                            Description = "Samverkan mot cyberspionage",
                            SegmentId = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VVCyberAware.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VVCyberAware.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VVCyberAware.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VVCyberAware.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.QuestionModel", b =>
                {
                    b.HasOne("VVCyberAware.Shared.Models.DbModels.SubCategoryModel", "SubCategory")
                        .WithMany("Questions")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SegmentModel", b =>
                {
                    b.HasOne("VVCyberAware.Shared.Models.DbModels.CategoryModel", "Category")
                        .WithMany("Segments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SubCategoryModel", b =>
                {
                    b.HasOne("VVCyberAware.Shared.Models.DbModels.SegmentModel", "Segment")
                        .WithMany("SubCategories")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.CategoryModel", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SegmentModel", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SubCategoryModel", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
