// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VVCyberAware.Data;

#nullable disable

namespace VVCyberAware.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240306124142_SeededmoreData")]
    partial class SeededmoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VVCyberAware.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Info om bedrägeri",
                            Name = "Att skydda sig mot bedrägerier"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Digital säkerhet på företag",
                            Name = "Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Allmänt om cyberspionage",
                            Name = " Cyberspionage"
                        });
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Explanation = "Banker och andra finansiella institutioner begär aldrig känslig information såsom kontonummer eller lösenord via telefon. Detta är ett klassiskt tecken på telefonbedrägeri.",
                            QuestionText = "Du får ett oväntat telefonsamtal från någon som påstår sig vara från din bank. Personen ber dig bekräfta ditt kontonummer och lösenord för att \"säkerställa din kontos säkerhet\" efter en påstådd säkerhetsincident. Hur bör du tolka denna situation?",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Explanation = "Begäran om pengar, särskilt under omständigheter där två personer aldrig har träffats fysiskt, är ett vanligt tecken på romansbedrägeri.",
                            QuestionText = "Efter flera månader av daglig kommunikation med någon du träffade på en datingsida, börjar personen berätta om en plötslig finansiell kris och ber om din hjälp genom att överföra pengar. Vad indikerar detta mest sannolikt?",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            Explanation = "Erbjudanden som lovar hög avkastning med liten eller ingen risk, särskilt via oönskade e-postmeddelanden, är ofta tecken på investeringsbedrägerier",
                            QuestionText = "Du får ett e-postmeddelande/samtal om ett exklusivt erbjudande att investera i ett startup-företag som påstås ha en revolutionerande ny teknologi, med garantier om exceptionellt hög avkastning på mycket kort tid. Hur bör du förhålla dig till erbjudandet?\r\n",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            Explanation = "Oidentifierade transaktioner på ditt kreditkortsutdrag är en stark indikation på att ditt kortnummer har komprometterats och använts för obehöriga köp, vilket är typiskt för kreditkortsbedrägeri.",
                            QuestionText = "Efter en online-shoppingrunda märker du oidentifierade transaktioner på ditt kreditkortsutdrag från företag du aldrig handlat från. Vad indikerar detta mest sannolikt?",
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            Explanation = "Denna fråga syftar till att öka medvetenheten om hur bedragare kan försöka manipulera människor i sina egna hem, ofta genom att erbjuda något som verkar vara för bra för att vara sant, som gratisprodukter eller tjänster, i utbyte mot personlig information eller finansiell data.",
                            QuestionText = "Vad är de vanligaste tecknen på att du kan vara måltavla för ett bedrägeri i hemmet?",
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            Explanation = " Denna fråga riktar in sig på att identifiera varningssignaler som kan tyda på att någon obehörigt använder din personliga information. Genom att känna till dessa tecken kan individer agera snabbt för att skydda sin finansiella hälsa och juridiska ställning.",
                            QuestionText = "Hur kan du upptäcka om någon har stulit din identitet?",
                            SubCategoryId = 6
                        });
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SegmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIsComplete")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Segments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Del 1",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Del 2",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Del 3",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Del 1",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Del 2",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Del 3",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Del 4",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Del 1",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Del 2",
                            UserIsComplete = "[]"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Del 3",
                            UserIsComplete = "[]"
                        });
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SubCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kreditkortsbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Romansbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Investeringsbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Telefonbedrägeri",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bedrägerier i hemmet",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Identitetsstöld",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Nätfiske och bluffmejl",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Investeringsbedrägeri på nätet",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Abonnemangsfällor och falska fakturor",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ransomware",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 11,
                            Description = "Statistik och förhållningssätt",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 12,
                            Description = "Digital säkerhet på företag",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Risker och beredskap",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 14,
                            Description = "Aktörer inom cyberbrott",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ökad digital närvaro och distansarbete",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 16,
                            Description = "Cyberangrepp mot känsliga sektorer",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Cyberrånet mot Mersk",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 18,
                            Description = "Social engineering",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 19,
                            Description = "Nätfiske och skräppost",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 20,
                            Description = "Vishing",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 21,
                            Description = "Varning för vishing",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 22,
                            Description = "Identifiera VD-mejl",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 23,
                            Description = "Öneangrepp och presentkortsbluffar",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "Virus, maskar och trojaner",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 25,
                            Description = "Nätverksintrång",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 26,
                            Description = "Dataintrång",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 27,
                            Description = "Hackad!",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 28,
                            Description = "Vägarna in",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 29,
                            Description = "Utpressningsvirus",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 30,
                            Description = "Attacker mot servrar",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 31,
                            Description = "Cyberangrepp i Norden",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 32,
                            Description = "It-brottslingarnas verktyg",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 33,
                            Description = "Mirai, Wannacry och fallet Düsseldorf",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 34,
                            Description = "De sårbara molnen",
                            SegmentId = 7
                        },
                        new
                        {
                            Id = 35,
                            Description = "Allmänt om cyberspionage",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 36,
                            Description = "Metoder för cyberspionage",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 37,
                            Description = "Säkerhetsskyddslagen",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 38,
                            Description = "Cyberspionagets aktörer",
                            SegmentId = 8
                        },
                        new
                        {
                            Id = 39,
                            Description = "Värvningsförsök",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 40,
                            Description = "Affärsspionage",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 41,
                            Description = "Påverkanskampanjer",
                            SegmentId = 9
                        },
                        new
                        {
                            Id = 42,
                            Description = "Svensk underrättelsetjänst och cyberförsvar",
                            SegmentId = 10
                        },
                        new
                        {
                            Id = 43,
                            Description = "Signalspaning, informationssäkerhet och 5G",
                            SegmentId = 10
                        },
                        new
                        {
                            Id = 44,
                            Description = "Samverkan mot cyberspionage",
                            SegmentId = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VVCyberAware.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VVCyberAware.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VVCyberAware.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VVCyberAware.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.QuestionModel", b =>
                {
                    b.HasOne("VVCyberAware.Shared.Models.DbModels.SubCategoryModel", "SubCategory")
                        .WithMany("Questions")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SegmentModel", b =>
                {
                    b.HasOne("VVCyberAware.Shared.Models.DbModels.CategoryModel", "Category")
                        .WithMany("Segments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SubCategoryModel", b =>
                {
                    b.HasOne("VVCyberAware.Shared.Models.DbModels.SegmentModel", "Segment")
                        .WithMany("SubCategories")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.CategoryModel", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SegmentModel", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("VVCyberAware.Shared.Models.DbModels.SubCategoryModel", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
